### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by bragefuglseth** [vtrlx/parchment#3]
Hi! Thought you might want to know that the app name “Paper” is in use by [another app](https://flathub.org/apps/io.posidon.Paper). Development on it seems to have stagnated, but it still managed to make a name for itself while it was active.

To make matters even more impractical, GNOME's next-generation document viewer, set to become the default in a future release, is called [Papers](https://flathub.org/apps/org.gnome.Papers) :smile: 

To make this app stand out a little more, you might want to go with something different that's still paper related (e.g. Cellulose, Parchment, Vellum, Manila, Worksheets, etc.).

**Comment by vtrlx** [comment]
I'll definitely have to keep this in mind.

**Comment by vtrlx** [comment]
Thank you for the excellent suggestion of Parchment, it perfectly fits the vibe I am aiming for with this project.
